// autopackage file for coapp.toolkit

package {
    location: "http://coapp.org/repository/${OutputFilename}";
    feed: "http://coapp.org/repository/packages.atom.xml";
    publisher: "CoApp Project";
}


metadata {
    licenses : {
        Apache20
    };
    
}

identity[CoApp Project] {
    name : "CoApp Project, Outercurve Foundation";
    email: "coapp@coapp.org";
    website: "http://coapp.org";
}
