//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoApp.Autopackage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CoApp.Autopackage.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid package name was found in the property sheet..
        /// </summary>
        internal static string AP100 {
            get {
                return ResourceManager.GetString("AP100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package name {0} is invalid. It must only contain ASCII letters, numbers, underscores, dashes and periods..
        /// </summary>
        internal static string AP101 {
            get {
                return ResourceManager.GetString("AP101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package version {0} is invalid. The possible versions are auto or x.x.y.y where x is an integer between 0 and 255 and y is an integer between 0 and 65535..
        /// </summary>
        internal static string AP102 {
            get {
                return ResourceManager.GetString("AP102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package architecture {0} is invalid. The possible values for arch are auto or x86, x64, or any..
        /// </summary>
        internal static string AP103 {
            get {
                return ResourceManager.GetString("AP103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The architecture could not be discovered from file: {0}.
        /// </summary>
        internal static string AP104 {
            get {
                return ResourceManager.GetString("AP104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The version could not be discovered from file: {0}.
        /// </summary>
        internal static string AP105 {
            get {
                return ResourceManager.GetString("AP105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon file at {0} is not a PNG with dimensions {1}x{2}..
        /// </summary>
        internal static string AP106 {
            get {
                return ResourceManager.GetString("AP106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The icon file at {0} could not be opened..
        /// </summary>
        internal static string AP107 {
            get {
                return ResourceManager.GetString("AP107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short description file at {0} was too long. A short description must be no longer than {1} characters..
        /// </summary>
        internal static string AP108 {
            get {
                return ResourceManager.GetString("AP108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short description file at {0} isn&apos;t a text file..
        /// </summary>
        internal static string AP109 {
            get {
                return ResourceManager.GetString("AP109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The short description file at {0} could not be opened..
        /// </summary>
        internal static string AP110 {
            get {
                return ResourceManager.GetString("AP110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description file at {0} isn&apos;t a text file..
        /// </summary>
        internal static string AP111 {
            get {
                return ResourceManager.GetString("AP111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description file at {0} could not be opened..
        /// </summary>
        internal static string AP112 {
            get {
                return ResourceManager.GetString("AP112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license url  {0} is not a valid URI or does not have a valid protocol. URLs must use the HTTP or HTTPS protocol.
        /// </summary>
        internal static string AP113 {
            get {
                return ResourceManager.GetString("AP113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license file at {0} isn&apos;t a text file..
        /// </summary>
        internal static string AP114 {
            get {
                return ResourceManager.GetString("AP114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The license file at {0} for the {1} role could not be opened..
        /// </summary>
        internal static string AP115 {
            get {
                return ResourceManager.GetString("AP115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License Url was provided without any license text, which is required. The license URL will not be included in the output file..
        /// </summary>
        internal static string AP116 {
            get {
                return ResourceManager.GetString("AP116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The feed url  {0} is not a valid URI. URLs must use the HTTP or HTTPS protocol..
        /// </summary>
        internal static string AP118 {
            get {
                return ResourceManager.GetString("AP118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The original location url  {0} does not have a valid protocol. URLs must use the HTTP or HTTPS protocol..
        /// </summary>
        internal static string AP120 {
            get {
                return ResourceManager.GetString("AP120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The original location url  {0} is not a valid URI..
        /// </summary>
        internal static string AP121 {
            get {
                return ResourceManager.GetString("AP121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate file was specified..
        /// </summary>
        internal static string AP122 {
            get {
                return ResourceManager.GetString("AP122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No certificate password was specified..
        /// </summary>
        internal static string AP123 {
            get {
                return ResourceManager.GetString("AP123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Pfx file {0} is not valid..
        /// </summary>
        internal static string AP124 {
            get {
                return ResourceManager.GetString("AP124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were no code signing certificates, with private keys, in the Pfx file {0}..
        /// </summary>
        internal static string AP125 {
            get {
                return ResourceManager.GetString("AP125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A public key token could not be extracted from the Pfx file {0}.
        /// </summary>
        internal static string AP126 {
            get {
                return ResourceManager.GetString("AP126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your publisher name could not be extracted from {0}. The publisher name is after the &apos;CN=&apos; in your certificate subject name..
        /// </summary>
        internal static string AP127 {
            get {
                return ResourceManager.GetString("AP127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A publisher email could not be extracted from {0}..
        /// </summary>
        internal static string AP128 {
            get {
                return ResourceManager.GetString("AP128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publisher email {0} is not a valid email address..
        /// </summary>
        internal static string AP129 {
            get {
                return ResourceManager.GetString("AP129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publish date entered, {0}, could not be parsed..
        /// </summary>
        internal static string AP130 {
            get {
                return ResourceManager.GetString("AP130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You haven&apos;t specified any roles to create. You can&apos;t have a CoApp package without roles; that&apos;s lunacy!.
        /// </summary>
        internal static string AP131 {
            get {
                return ResourceManager.GetString("AP131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The major.minor version {0} is invalid..
        /// </summary>
        internal static string AP132 {
            get {
                return ResourceManager.GetString("AP132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The dependency {0} is not satisfiable. It must be installed..
        /// </summary>
        internal static string AP133 {
            get {
                return ResourceManager.GetString("AP133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The policy  {0} is invalid..
        /// </summary>
        internal static string AP134 {
            get {
                return ResourceManager.GetString("AP134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The binding version {0} is too high. It must be less than that package version..
        /// </summary>
        internal static string AP135 {
            get {
                return ResourceManager.GetString("AP135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} could not be signed..
        /// </summary>
        internal static string AP136 {
            get {
                return ResourceManager.GetString("AP136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The manifest {0} couldn&apos;t be embedded in {1}.
        /// </summary>
        internal static string AP137 {
            get {
                return ResourceManager.GetString("AP137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a CAT file for {0}.
        /// </summary>
        internal static string AP138 {
            get {
                return ResourceManager.GetString("AP138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [{0}] failed strong naming.
        /// </summary>
        internal static string AP139 {
            get {
                return ResourceManager.GetString("AP139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract public key from [{0}].
        /// </summary>
        internal static string AP140 {
            get {
                return ResourceManager.GetString("AP140", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Policy assembly {0} could not be built..
        /// </summary>
        internal static string AP141 {
            get {
                return ResourceManager.GetString("AP141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candle.exe (from Wix) failed. Light.exe output: {0}.
        /// </summary>
        internal static string AP142 {
            get {
                return ResourceManager.GetString("AP142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.exe (from Wix) failed. Light.exe output: {0}.
        /// </summary>
        internal static string AP143 {
            get {
                return ResourceManager.GetString("AP143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to candle.exe from WiX could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP144 {
            get {
                return ResourceManager.GetString("AP144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to light.exe from WiX could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP145 {
            get {
                return ResourceManager.GetString("AP145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mt.exe from the Windows SDK could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP146 {
            get {
                return ResourceManager.GetString("AP146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to makecat.exe from the Windows SDK could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP147 {
            get {
                return ResourceManager.GetString("AP147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to al.exe from the Windows SDK could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP148 {
            get {
                return ResourceManager.GetString("AP148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to signtool.exe from the Windows SDK could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP149 {
            get {
                return ResourceManager.GetString("AP149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sn.exe from the Windows SDK could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP150 {
            get {
                return ResourceManager.GetString("AP150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pktExtract.exe from the Windows SDK could not be found. Are you sure it&apos;s installed?.
        /// </summary>
        internal static string AP151 {
            get {
                return ResourceManager.GetString("AP151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global-bin must be set to true or false.
        /// </summary>
        internal static string AP152 {
            get {
                return ResourceManager.GetString("AP152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Exe file with the output path of {0} could not be found in any of the include directives in the the App rule..
        /// </summary>
        internal static string AP153 {
            get {
                return ResourceManager.GetString("AP153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The publisher website url  {0} is not a valid URI. URLs must use the HTTP or HTTPS protocol..
        /// </summary>
        internal static string AP155 {
            get {
                return ResourceManager.GetString("AP155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate file {0} has expired. Signing can only be done by a valid certificate..
        /// </summary>
        internal static string AP156 {
            get {
                return ResourceManager.GetString("AP156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is not signed with the certificate in {1}..
        /// </summary>
        internal static string AP157 {
            get {
                return ResourceManager.GetString("AP157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is not signed. All binary files must be signed. If you&apos;d like unsigned binaries to be automatically signed, use the &quot;autosign&quot; argument when running autopackage..
        /// </summary>
        internal static string AP158 {
            get {
                return ResourceManager.GetString("AP158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The certificate on the file {0} could not be opened to be evaluated..
        /// </summary>
        internal static string AP159 {
            get {
                return ResourceManager.GetString("AP159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path description {0} is not a valid simple subpath. A simple subpath may not contain a drive letter, colon, wildcards, any path part section with just &quot;.&quot;or &quot;..&quot; and may not start with a slash..
        /// </summary>
        internal static string AP160 {
            get {
                return ResourceManager.GetString("AP160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No name was entered for a contributor..
        /// </summary>
        internal static string AP161 {
            get {
                return ResourceManager.GetString("AP161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contributor website url  {0} does not have a valid protocol. URLs must use the HTTP or HTTPS protocol..
        /// </summary>
        internal static string AP162 {
            get {
                return ResourceManager.GetString("AP162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contributor website url  {0} is not a valid URI..
        /// </summary>
        internal static string AP163 {
            get {
                return ResourceManager.GetString("AP163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The contributor email {0} is not a valid email address..
        /// </summary>
        internal static string AP164 {
            get {
                return ResourceManager.GetString("AP164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest bootstrap manifest could not be downloaded from {0}. Check your network connection and try again..
        /// </summary>
        internal static string AP165 {
            get {
                return ResourceManager.GetString("AP165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The bug tracker url  {0} is not a valid URI. URLs must use the HTTP or HTTPS protocol..
        /// </summary>
        internal static string AP167 {
            get {
                return ResourceManager.GetString("AP167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The path description {0} is not a valid simple subpath. A simple subpath may not contain a drive letter, colon, wildcards, any path part section with just &quot;.&quot;or &quot;..&quot; and may not start with a slash..
        /// </summary>
        internal static string AP168 {
            get {
                return ResourceManager.GetString("AP168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be set to true or false.
        /// </summary>
        internal static string AP169 {
            get {
                return ResourceManager.GetString("AP169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global must be set to true or false..
        /// </summary>
        internal static string AP170 {
            get {
                return ResourceManager.GetString("AP170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing application files for app role....
        /// </summary>
        internal static string AppCreation {
            get {
                return ResourceManager.GetString("AppCreation", resourceCulture);
            }
        }
        
        internal static byte[] blankicon {
            get {
                object obj = ResourceManager.GetObject("blankicon", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] coapp_managed_bootstrap {
            get {
                object obj = ResourceManager.GetObject("coapp_managed_bootstrap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] coapp_native_bootstrap {
            get {
                object obj = ResourceManager.GetObject("coapp_native_bootstrap", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Building your package file. This could take a few minutes....
        /// </summary>
        internal static string CreatingMSI {
            get {
                return ResourceManager.GetString("CreatingMSI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create a CDF for manifest {0}.
        /// </summary>
        internal static string FailedCDFCreation {
            get {
                return ResourceManager.GetString("FailedCDFCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fatal.
        /// </summary>
        internal static string Fatal {
            get {
                return ResourceManager.GetString("Fatal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  finished..
        /// </summary>
        internal static string Finished {
            get {
                return ResourceManager.GetString("Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use --help for command line assistance..
        /// </summary>
        internal static string ForCommandLineHelp {
            get {
                return ResourceManager.GetString("ForCommandLineHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage:
        ///-------
        ///
        ///Autopackage [options] &lt;file.autopkg&gt;
        ///
        ///	&lt;file.autopkg&gt; - the property sheet file for the package to create
        ///
        ///Options:
        ///--------
        ///    --help                      this help
        ///    --nologo                    don&apos;t display the logo
        ///    --load-config=&lt;file&gt;        loads configuration from &lt;file&gt;
        ///    --verbose                   prints verbose messages (not used now)
        ///
        ///	--certificate-path=&lt;c.pfx&gt;  path to load signing certificate (w/pvt key)
        ///    --password=&lt;pwd&gt;            password for cert [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HelpText {
            get {
                return ResourceManager.GetString("HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing command..
        /// </summary>
        internal static string MissingCommand {
            get {
                return ResourceManager.GetString("MissingCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No architecture for the package was specified or it was invalid..
        /// </summary>
        internal static string MissingPackageArch {
            get {
                return ResourceManager.GetString("MissingPackageArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No version for the package was specified or it was invalid..
        /// </summary>
        internal static string MissingPackageVersion {
            get {
                return ResourceManager.GetString("MissingPackageVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No binary file was provided..
        /// </summary>
        internal static string NoBinaryFileProvided {
            get {
                return ResourceManager.GetString("NoBinaryFileProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No config file was loaded..
        /// </summary>
        internal static string NoConfigFileLoaded {
            get {
                return ResourceManager.GetString("NoConfigFileLoaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning: .
        /// </summary>
        internal static string Scanning {
            get {
                return ResourceManager.GetString("Scanning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scanning installed packages....
        /// </summary>
        internal static string ScanningInstalledPackages {
            get {
                return ResourceManager.GetString("ScanningInstalledPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating and signing assemblies for shared library....
        /// </summary>
        internal static string SharedLibCreation {
            get {
                return ResourceManager.GetString("SharedLibCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // this file gets loaded before the ones passed on the command line.
        ///
        ///templates {
        ///   native-publisher-configuration : @&quot;&lt;?xml version=&quot;&quot;1.0&quot;&quot; encoding=&quot;&quot;UTF-8&quot;&quot; standalone=&quot;&quot;yes&quot;&quot;?&gt;
        ///&lt;assembly xmlns=&quot;&quot;urn:schemas-microsoft-com:asm.v1&quot;&quot; manifestVersion=&quot;&quot;1.0&quot;&quot;&gt;
        ///    &lt;assemblyIdentity type=&quot;&quot;win32-policy&quot;&quot; publicKeyToken=&quot;&quot;${this.Assembly.PublicKeyToken}&quot;&quot; name=&quot;&quot;policy.${this.OldAssembly.MajorMinorVersion}.${this.Assembly.Name}&quot;&quot; version=&quot;&quot;${this.Assembly.Version}&quot;&quot; processorArchitecture=&quot;&quot;${this.Assembly [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string template_autopkg {
            get {
                return ResourceManager.GetString("template_autopkg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking up tool locations....
        /// </summary>
        internal static string ToolLookup {
            get {
                return ResourceManager.GetString("ToolLookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown command [{0}].
        /// </summary>
        internal static string UnknownCommand {
            get {
                return ResourceManager.GetString("UnknownCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown parameter [--{0}].
        /// </summary>
        internal static string UnknownParameter {
            get {
                return ResourceManager.GetString("UnknownParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Wix &gt;
        ///  &lt;!-- language must be figured out!--&gt;
        ///  &lt;Product Language=&quot;1033&quot;&gt;
        ///      &lt;Package InstallerVersion=&quot;301&quot; Compressed=&quot;yes&quot; InstallPrivileges=&quot;limited&quot; /&gt;
        ///      &lt;Media Id=&quot;1&quot; Cabinet=&quot;cab.cab&quot; EmbedCab=&quot;yes&quot; CompressionLevel=&quot;high&quot;/&gt;
        ///      &lt;!-- CoApp Packages must be not be allusers, not per-user (GS)--&gt;
        ///      &lt;Property Id=&quot;ALLUSERS&quot; Secure=&quot;yes&quot; /&gt;
        ///    
        ///      &lt;!-- add in the custom action native bootstrap--&gt;
        ///
        ///      &lt;Binary Id=&quot;native_bootstrap.exe&quot;/&gt; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WixTemplate {
            get {
                return ResourceManager.GetString("WixTemplate", resourceCulture);
            }
        }
    }
}
